---
title: "III Escuela Latinoamericana de Evolución"
subtitle: "**BIO5751-4** *Quantitative genetics: from genes to phenotypes and its evolution*"
date: "05/12/2017 - 18/12/2017"
output:
  html_document:
    number_sections: false
    toc: true
    theme: yeti
    toc_depth: 3
    toc_float: 
      collapsed: false
      smooth_scroll: false
---

# Intro

Most of the characters of economic, ecological and evolutionary interest are quantitative, that is, they present continuous variation and a complex genetic base. The field of quantitative genetics provides a framework for understanding the patterns of variation, inheritance, and evolutionary dynamics of such quantitative traits. In this course we will present the basic theory of the field of quantitative genetics and its connections for applications in animal and plant breeding, identification of molecular variants underlying these traits and patterns / processes of phenotype evolution (both micro- and macroevolutionary). Where possible the course will emphasize the actual biological complexity while working with a perspective that considers multiple characters (multivariate quantitative genetics). The course begins with a basic education to make it accessible, but is a course primarily geared toward students with some previous experience in genetics and / or evolutionary biology. Some experience with statistics (especially multivariate) will provide an important background but it is not a requirement.

# Objectives

- Introduction to Quantitative Genetics
- Genetic Architecture of quantitative traits
- Molecular Basis of variation and evolutionary response
- Characterizing genetic Architecture (QTL and GWAS)
- Multiple traits and Pleiotropy
- Gene interaction (Epistasis)
- Modularity and Integration
- Evolvability and Constraints
- Environmental variation and genotype-environment interaction
- Measuring Natural Selection
- Micro- and Macroevolution
- Towards and integrative approach: genes, expression and quantitative traits data

# References

- Lynch and Walsh (1998) - Genetics and Analysis of Quantitative Traits - Sinauer Associates

# Teachers

- [Gabriel Marroig](http://www.ib.usp.br/depto-genetica-bio-evolutiva/corpo-docente/533-prof-dr-gabriel-henrique-marroig-zambonato.html) - Universidade de São Paulo

- [Diogo Meyer](http://www.ib.usp.br/genevol/) - Universidade de São Paulo 

- [Julien Ayroles](http://www.ayroleslab.com/) - Princeton University

- [Jason Wolf](http://www.evolutionarygenetics.org/) - University of Bath

# Details

- Dates: 05/12/2017 - 18/12/2017
- Time: 14h às 18h 
- Credits: 04 
- Available places: 50, including special students

# Registration

- Aluno do IB/USP traz o [formulário](files/Matricula_Aluno_Regular.rtf) preenchido e assinado;
- Aluno USP faz matrícula no Janus em sua secretaria de Pós-Graduação;
- Alunos externos fazem inscrição por e-mail, conforme instruções em( [http://www.ib.usp.br/cpg/matricula/especial.html](http://www.ib.usp.br/cpg/matricula/especial.html)